# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
AWS_ACCESS_KEY: "AKIAJZQUX2N3CVAO3PMA"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "grammable1"
AWS_REGION: "us-east-1"

#Stripe
#These must be changed to non-test keys if using real payments in the future
#SECRET_KEY: "sk_test_Mx0R9YuhsfiUAralJDeW2AAE"
#PUBLISHABLE_KEY: "pk_test_30tBvJBVCswSyoBxlGvwjSJW"